languageCode = "en"
[languages]
  [languages.en]
    [languages.en.params]
      dateFormat = "2 January 2006"
      languageName = "English"
      displayName = "EN"
      isoCode = "en"
      weight = 1
      rtl = false


title = "Rebecca Sutton Koeser"
# logo = "img/logo.png"
# copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Rebecca Sutton Koeser"
#   image = "img/blowfish_logo.png"
#   headline = "I'm only human"
  bio = "Lead Research Software Engineer at the Center for Digital Humanities @ Princeton."
  links = [
#     { email = "mailto:hello@your_domain.com" },
    { link = "https://rlskoeser.github.io/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/rlskoeser" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://www.linkedin.com/in/rebeccasuttonkoeser/" },
    { mastodon = "https://hcommons.social/@rsk" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
    { orcid = "https://orcid.org/0000-0002-8762-8057" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/suttonkoeser" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
    { blueskey = "https://bsky.app/profile/suttonkoeser.bsky.social" },
  ]
