# Site wide configuration

title:            Rebecca Sutton Koeser
locale:           en_US
url:              https://rlskoeser.github.io
# url to use for finding mentions, even when running in development
public_url:       https://rlskoeser.github.io
timezone: "America/New_York"


# Jekyll configuration

# permalink:   /:categories/:title/
# NOTE: "pretty" permalink = /:categories/:year/:month/:day/:title/
permalink:   pretty
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions: https://twitter.com

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

collections:
  updates:
    output: true
    permalink: /updates/:path/
  tag_pages:
    output: true
    permalink: /tags/:path/


defaults:
- scope:
    path: ""
    type: updates
  values:
    layout: update
- scope:
    path: ""
    type: tag_pages
  values:
    layout: tag


# rake task configuration
update:
  template: rake_templates/update.md
  extension: md
  bridgy_omit_link: true
editor: subl -n -w

# Site owner
owner:
  name: Rebecca Sutton Koeser
  avatar: bec.png
  uri: 'https://rlskoeser.github.io/#rsk'
  bio: "Lead Developer at Princeton University Center for Digital Humanities, PhD in English Literature."
  email:
  disqus-shortname:
  twitter: suttonkoeser
  facebook: #username
  google:
    plus: #username
    analytics: UA-333498-6
    verify: c6VMioDMUJeS7fIotCrupOzK0s2FbDJ7skLNcvumLng
    ad-client:
    ad-slot:
  bing-verify:
  github: rlskoeser
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: rebeccasuttonkoeser
  orcid: 0000-0002-8762-8057
  keybase: suttonkoeser
  hcommons: suttonkoeser
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

post_extension: md

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile",
  "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace",
  "test", "spec", "Gruntfile.js", "package.json", "node_modules",
  "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "rake_templates"]
