baseURL: https://rlskoeser.github.io
disablePathToLower: true
languageCode: en-us
title: Rebecca Sutton Koeser
theme: ananke


Paginate: 10


params:
  # body_classes: "noto bg-near-white"
  # post_content_classes: "noto"
  custom_css: 
    - "local.scss"
  disable_share: true
  # text_color = ""
  author: Rebecca Sutton Koeser
  favicon: /favicon.ico
  # site_logo = ""
  # description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  recent_posts_number: 10
  ananke_socials:
  - name: twitter
    url: https://twitter.com/suttonkoeser
  - name: github
    url: https://github.com/rlskoeser
  - name: linkedin
    url: https://www.linkedin.com/in/rebeccasuttonkoeser/


# configure to render raw html in posts

markup:
  goldmark:
    renderer:
      unsafe: true
      attribute: true
